/**
 * Grocery list data access layer
 */
import { getDatabase } from '../../database/db';
import { GroceryItem, NewGroceryItem } from '../../database/types';

/**
 * Get all grocery items
 */
export async function getAllGroceryItems(): Promise<GroceryItem[]> {
  const db = getDatabase();
  return await db.getAllAsync<GroceryItem>(
    'SELECT * FROM grocery_items ORDER BY is_purchased ASC, name ASC'
  );
}

/**
 * Get unpurchased grocery items
 */
export async function getUnpurchasedItems(): Promise<GroceryItem[]> {
  const db = getDatabase();
  return await db.getAllAsync<GroceryItem>(
    'SELECT * FROM grocery_items WHERE is_purchased = 0 ORDER BY name ASC'
  );
}

/**
 * Create a new grocery item
 */
export async function createGroceryItem(item: NewGroceryItem): Promise<number> {
  const db = getDatabase();
  const result = await db.runAsync(
    `INSERT INTO grocery_items (pantry_item_id, name, quantity, unit, is_purchased, auto_generated, source) 
     VALUES (?, ?, ?, ?, ?, ?, ?)`,
    [
      item.pantry_item_id ?? null,
      item.name,
      item.quantity,
      item.unit,
      item.is_purchased,
      item.auto_generated,
      item.source ?? null,
    ]
  );
  return result.lastInsertRowId;
}

/**
 * Mark grocery item as purchased
 */
export async function markItemPurchased(id: number): Promise<void> {
  const db = getDatabase();
  await db.runAsync('UPDATE grocery_items SET is_purchased = 1 WHERE id = ?', [id]);
}

/**
 * Delete grocery item
 */
export async function deleteGroceryItem(id: number): Promise<void> {
  const db = getDatabase();
  await db.runAsync('DELETE FROM grocery_items WHERE id = ?', [id]);
}

/**
 * Clear all purchased items
 */
export async function clearPurchasedItems(): Promise<void> {
  const db = getDatabase();
  await db.runAsync('DELETE FROM grocery_items WHERE is_purchased = 1');
}

/**
 * Get grocery item by pantry item ID
 */
export async function getGroceryItemByPantryId(pantryItemId: number): Promise<GroceryItem | null> {
  const db = getDatabase();
  return await db.getFirstAsync<GroceryItem>(
    'SELECT * FROM grocery_items WHERE pantry_item_id = ? AND auto_generated = 1',
    [pantryItemId]
  );
}

/**
 * Update grocery item
 */
export async function updateGroceryItem(id: number, updates: Partial<NewGroceryItem>): Promise<void> {
  const db = getDatabase();
  const fields: string[] = [];
  const values: any[] = [];

  if (updates.name !== undefined) {
    fields.push('name = ?');
    values.push(updates.name);
  }
  if (updates.quantity !== undefined) {
    fields.push('quantity = ?');
    values.push(updates.quantity);
  }
  if (updates.unit !== undefined) {
    fields.push('unit = ?');
    values.push(updates.unit);
  }
  if (updates.is_purchased !== undefined) {
    fields.push('is_purchased = ?');
    values.push(updates.is_purchased);
  }

  if (fields.length > 0) {
    values.push(id);
    await db.runAsync(
      `UPDATE grocery_items SET ${fields.join(', ')} WHERE id = ?`,
      values
    );
  }
}

/**
 * Get auto-generated grocery items
 */
export async function getAutoGeneratedItems(): Promise<GroceryItem[]> {
  const db = getDatabase();
  return await db.getAllAsync<GroceryItem>(
    'SELECT * FROM grocery_items WHERE auto_generated = 1 ORDER BY name ASC'
  );
}

/**
 * Get manually added grocery items
 */
export async function getManualItems(): Promise<GroceryItem[]> {
  const db = getDatabase();
  return await db.getAllAsync<GroceryItem>(
    'SELECT * FROM grocery_items WHERE auto_generated = 0 ORDER BY name ASC'
  );
}
