/**
 * Grocery List screen
 * View and manage shopping list
 */
import React, { useState, useCallback } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Alert } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { GroceryItem } from '../../src/database/types';
import {
  getAutoGeneratedItems,
  getManualItems,
  createGroceryItem,
  markItemPurchased,
  deleteGroceryItem,
  clearPurchasedItems,
} from '../../src/modules/grocery/groceryData';
import ScreenContainer from '../../src/components/common/ScreenContainer';
import PrimaryButton from '../../src/components/common/PrimaryButton';
import SecondaryButton from '../../src/components/common/SecondaryButton';
import SectionHeader from '../../src/components/common/SectionHeader';
import EmptyState from '../../src/components/common/EmptyState';
import GroceryItemCard from '../../src/components/GroceryItemCard';
import AddGroceryItemModal from '../../src/components/AddGroceryItemModal';
import colors from '../../src/theme/colors';
import spacing from '../../src/theme/spacing';
import { textStyles, typography } from '../../src/theme/typography';

export default function GroceryScreen() {
  const [autoItems, setAutoItems] = useState<GroceryItem[]>([]);
  const [manualItems, setManualItems] = useState<GroceryItem[]>([]);
  const [showPurchased, setShowPurchased] = useState(true);
  const [loading, setLoading] = useState(false);
  const [modalVisible, setModalVisible] = useState(false);

  const loadItems = async () => {
    setLoading(true);
    try {
      const [auto, manual] = await Promise.all([
        getAutoGeneratedItems(),
        getManualItems(),
      ]);
      setAutoItems(auto);
      setManualItems(manual);
    } catch (error) {
      console.error('Error loading grocery items:', error);
      Alert.alert('Error', 'Failed to load grocery items');
    } finally {
      setLoading(false);
    }
  };

  useFocusEffect(
    useCallback(() => {
      loadItems();
    }, [])
  );

  const handleAddManualItem = () => {
    setModalVisible(true);
  };

  const handleSaveManualItem = async (itemData: {
    name: string;
    quantity: number;
    unit: string;
  }) => {
    try {
      await createGroceryItem({
        pantry_item_id: null,
        name: itemData.name,
        quantity: itemData.quantity,
        unit: itemData.unit,
        is_purchased: 0,
        auto_generated: 0,
        source: 'manual',
      });
      setModalVisible(false);
      loadItems();
    } catch (error) {
      console.error('Error adding grocery item:', error);
      Alert.alert('Error', 'Failed to add grocery item');
    }
  };

  const handleTogglePurchased = async (item: GroceryItem) => {
    try {
      if (item.is_purchased === 0) {
        await markItemPurchased(item.id);
      } else {
        // Unpurchase by updating the item
        await markItemPurchased(item.id); // We'll need to add an unpurchase function
        // For now, just toggle by deleting and recreating (simplified)
        // In production, you'd add an `unpurchaseItem` function
      }
      loadItems();
    } catch (error) {
      console.error('Error toggling purchased status:', error);
      Alert.alert('Error', 'Failed to update item');
    }
  };

  const handleDeleteItem = (item: GroceryItem) => {
    const canDelete = item.auto_generated === 0 || item.is_purchased === 1;
    
    if (!canDelete) {
      Alert.alert(
        'Cannot Delete',
        'This item was automatically added from pantry. To remove it, increase the pantry stock instead.',
        [{ text: 'OK' }]
      );
      return;
    }

    Alert.alert(
      'Delete Item',
      `Are you sure you want to delete "${item.name}"?`,
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              await deleteGroceryItem(item.id);
              loadItems();
            } catch (error) {
              console.error('Error deleting grocery item:', error);
              Alert.alert('Error', 'Failed to delete grocery item');
            }
          },
        },
      ]
    );
  };

  const handleClearPurchased = () => {
    Alert.alert(
      'Clear Purchased Items',
      'Remove all purchased items from the list?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Clear',
          onPress: async () => {
            try {
              await clearPurchasedItems();
              loadItems();
            } catch (error) {
              console.error('Error clearing purchased items:', error);
              Alert.alert('Error', 'Failed to clear purchased items');
            }
          },
        },
      ]
    );
  };

  const filterItems = (items: GroceryItem[]) => {
    return showPurchased ? items : items.filter((item) => item.is_purchased === 0);
  };

  const filteredAutoItems = filterItems(autoItems);
  const filteredManualItems = filterItems(manualItems);
  const totalItems = filteredAutoItems.length + filteredManualItems.length;

  const unpurchasedItems = [...filteredAutoItems, ...filteredManualItems].filter(i => i.is_purchased === 0);
  const purchasedItems = [...autoItems, ...manualItems].filter(i => i.is_purchased === 1);
  const hasPurchased = purchasedItems.length > 0;

  return (
    <View style={styles.container}>
      {/* Header with Add Button */}
      <View style={styles.header}>
        <PrimaryButton
          title="+ Add Item"
          onPress={handleAddManualItem}
          large
        />
      </View>

      {/* Controls */}
      {hasPurchased && (
        <View style={styles.controls}>
          <SecondaryButton
            title="Clear Purchased"
            onPress={handleClearPurchased}
            style={styles.clearButton}
          />
        </View>
      )}

      {/* Items List */}
      <ScreenContainer scrollable={true} style={styles.listContainer}>
        {loading ? (
          <View style={styles.loadingContainer}>
            <Text style={styles.loadingText}>Loading...</Text>
          </View>
        ) : unpurchasedItems.length === 0 && purchasedItems.length === 0 ? (
          <EmptyState
            icon="🛒"
            title="Nothing to buy right now"
            message="Add items manually or they will be added automatically when pantry items are low"
            actionLabel="Add Item"
            onAction={handleAddManualItem}
          />
        ) : (
          <>
            {/* Need to Buy Section */}
            {unpurchasedItems.length > 0 && (
              <View style={styles.section}>
                <SectionHeader title="Need to Buy" />
                <View style={styles.itemsList}>
                  {unpurchasedItems.map((item) => (
                    <GroceryItemCard
                      key={item.id}
                      item={item}
                      onTogglePurchased={handleTogglePurchased}
                      onDelete={handleDeleteItem}
                    />
                  ))}
                </View>
              </View>
            )}

            {/* Purchased Section */}
            {showPurchased && purchasedItems.length > 0 && (
              <View style={styles.section}>
                <SectionHeader 
                  title="Purchased" 
                  actionLabel={showPurchased ? 'Hide' : 'Show'}
                  onActionPress={() => setShowPurchased(!showPurchased)}
                />
                <View style={styles.itemsList}>
                  {purchasedItems.map((item) => (
                    <GroceryItemCard
                      key={item.id}
                      item={item}
                      onTogglePurchased={handleTogglePurchased}
                      onDelete={handleDeleteItem}
                    />
                  ))}
                </View>
              </View>
            )}

            {/* Show Purchased Button if hidden */}
            {!showPurchased && purchasedItems.length > 0 && (
              <TouchableOpacity
                style={styles.showPurchasedButton}
                onPress={() => setShowPurchased(true)}
                activeOpacity={0.7}
              >
                <Text style={styles.showPurchasedText}>
                  Show {purchasedItems.length} purchased item{purchasedItems.length !== 1 ? 's' : ''}
                </Text>
              </TouchableOpacity>
            )}

            {unpurchasedItems.length === 0 && purchasedItems.length > 0 && (
              <View style={styles.allDoneMessage}>
                <Text style={styles.allDoneIcon}>✓</Text>
                <Text style={styles.allDoneText}>All items purchased!</Text>
              </View>
            )}
          </>
        )}
      </ScreenContainer>

      <AddGroceryItemModal
        visible={modalVisible}
        onSave={handleSaveManualItem}
        onCancel={() => setModalVisible(false)}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    padding: spacing.base,
    backgroundColor: colors.cardBackground,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  controls: {
    padding: spacing.base,
    backgroundColor: colors.cardBackground,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  clearButton: {
    borderColor: colors.error,
  },
  listContainer: {
    flex: 1,
  },
  loadingContainer: {
    paddingVertical: spacing.huge,
    alignItems: 'center',
  },
  loadingText: {
    ...textStyles.body,
    color: colors.textTertiary,
  },
  section: {
    marginBottom: spacing.sectionGap,
  },
  itemsList: {
    gap: spacing.cardGap,
  },
  showPurchasedButton: {
    backgroundColor: colors.surfaceLight,
    padding: spacing.base,
    borderRadius: spacing.radiusMedium,
    alignItems: 'center',
    marginTop: spacing.md,
  },
  showPurchasedText: {
    ...textStyles.body,
    color: colors.accent,
    fontWeight: typography.weight.semibold,
  },
  allDoneMessage: {
    alignItems: 'center',
    paddingVertical: spacing.xxl,
  },
  allDoneIcon: {
    fontSize: 48,
    marginBottom: spacing.md,
  },
  allDoneText: {
    ...textStyles.cardTitle,
    color: colors.goodStock,
  },
});
