/**
 * Grocery List screen
 * View and manage shopping list
 */
import React, { useState, useCallback } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { GroceryItem } from '../../src/database/types';
import {
  getAutoGeneratedItems,
  getManualItems,
  createGroceryItem,
  markItemPurchased,
  deleteGroceryItem,
  clearPurchasedItems,
} from '../../src/modules/grocery/groceryData';
import GroceryItemCard from '../../src/components/GroceryItemCard';
import AddGroceryItemModal from '../../src/components/AddGroceryItemModal';

export default function GroceryScreen() {
  const [autoItems, setAutoItems] = useState<GroceryItem[]>([]);
  const [manualItems, setManualItems] = useState<GroceryItem[]>([]);
  const [showPurchased, setShowPurchased] = useState(true);
  const [loading, setLoading] = useState(false);
  const [modalVisible, setModalVisible] = useState(false);

  const loadItems = async () => {
    setLoading(true);
    try {
      const [auto, manual] = await Promise.all([
        getAutoGeneratedItems(),
        getManualItems(),
      ]);
      setAutoItems(auto);
      setManualItems(manual);
    } catch (error) {
      console.error('Error loading grocery items:', error);
      Alert.alert('Error', 'Failed to load grocery items');
    } finally {
      setLoading(false);
    }
  };

  useFocusEffect(
    useCallback(() => {
      loadItems();
    }, [])
  );

  const handleAddManualItem = () => {
    setModalVisible(true);
  };

  const handleSaveManualItem = async (itemData: {
    name: string;
    quantity: number;
    unit: string;
  }) => {
    try {
      await createGroceryItem({
        pantry_item_id: null,
        name: itemData.name,
        quantity: itemData.quantity,
        unit: itemData.unit,
        is_purchased: 0,
        auto_generated: 0,
        source: 'manual',
      });
      setModalVisible(false);
      loadItems();
    } catch (error) {
      console.error('Error adding grocery item:', error);
      Alert.alert('Error', 'Failed to add grocery item');
    }
  };

  const handleTogglePurchased = async (item: GroceryItem) => {
    try {
      if (item.is_purchased === 0) {
        await markItemPurchased(item.id);
      } else {
        // Unpurchase by updating the item
        await markItemPurchased(item.id); // We'll need to add an unpurchase function
        // For now, just toggle by deleting and recreating (simplified)
        // In production, you'd add an `unpurchaseItem` function
      }
      loadItems();
    } catch (error) {
      console.error('Error toggling purchased status:', error);
      Alert.alert('Error', 'Failed to update item');
    }
  };

  const handleDeleteItem = (item: GroceryItem) => {
    const canDelete = item.auto_generated === 0 || item.is_purchased === 1;
    
    if (!canDelete) {
      Alert.alert(
        'Cannot Delete',
        'This item was automatically added from pantry. To remove it, increase the pantry stock instead.',
        [{ text: 'OK' }]
      );
      return;
    }

    Alert.alert(
      'Delete Item',
      `Are you sure you want to delete "${item.name}"?`,
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              await deleteGroceryItem(item.id);
              loadItems();
            } catch (error) {
              console.error('Error deleting grocery item:', error);
              Alert.alert('Error', 'Failed to delete grocery item');
            }
          },
        },
      ]
    );
  };

  const handleClearPurchased = () => {
    Alert.alert(
      'Clear Purchased Items',
      'Remove all purchased items from the list?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Clear',
          onPress: async () => {
            try {
              await clearPurchasedItems();
              loadItems();
            } catch (error) {
              console.error('Error clearing purchased items:', error);
              Alert.alert('Error', 'Failed to clear purchased items');
            }
          },
        },
      ]
    );
  };

  const filterItems = (items: GroceryItem[]) => {
    return showPurchased ? items : items.filter((item) => item.is_purchased === 0);
  };

  const filteredAutoItems = filterItems(autoItems);
  const filteredManualItems = filterItems(manualItems);
  const totalItems = filteredAutoItems.length + filteredManualItems.length;

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.addButton}
          onPress={handleAddManualItem}
          activeOpacity={0.7}
        >
          <Text style={styles.addButtonText}>+ Add Item</Text>
        </TouchableOpacity>
      </View>

      <View style={styles.controls}>
        <TouchableOpacity
          style={styles.toggleButton}
          onPress={() => setShowPurchased(!showPurchased)}
          activeOpacity={0.7}
        >
          <Text style={styles.toggleButtonText}>
            {showPurchased ? 'Hide Purchased' : 'Show Purchased'}
          </Text>
        </TouchableOpacity>
        {autoItems.some((i) => i.is_purchased === 1) || manualItems.some((i) => i.is_purchased === 1) ? (
          <TouchableOpacity
            style={styles.clearButton}
            onPress={handleClearPurchased}
            activeOpacity={0.7}
          >
            <Text style={styles.clearButtonText}>Clear Purchased</Text>
          </TouchableOpacity>
        ) : null}
      </View>

      <ScrollView style={styles.list} contentContainerStyle={styles.listContent}>
        {loading ? (
          <Text style={styles.emptyText}>Loading...</Text>
        ) : totalItems === 0 ? (
          <View style={styles.emptyContainer}>
            <Text style={styles.emptyText}>No items in grocery list</Text>
            <Text style={styles.emptySubtext}>
              {showPurchased
                ? 'Add items manually or they will be added automatically when pantry items are low'
                : 'No unpurchased items'}
            </Text>
          </View>
        ) : (
          <>
            {filteredAutoItems.length > 0 && (
              <View style={styles.section}>
                <Text style={styles.sectionTitle}>Automatically Needed</Text>
                <Text style={styles.sectionSubtitle}>
                  From low-stock pantry items
                </Text>
                {filteredAutoItems.map((item) => (
                  <GroceryItemCard
                    key={item.id}
                    item={item}
                    onTogglePurchased={handleTogglePurchased}
                    onDelete={handleDeleteItem}
                  />
                ))}
              </View>
            )}

            {filteredManualItems.length > 0 && (
              <View style={styles.section}>
                <Text style={styles.sectionTitle}>Manually Added</Text>
                {filteredManualItems.map((item) => (
                  <GroceryItemCard
                    key={item.id}
                    item={item}
                    onTogglePurchased={handleTogglePurchased}
                    onDelete={handleDeleteItem}
                  />
                ))}
              </View>
            )}
          </>
        )}
      </ScrollView>

      <AddGroceryItemModal
        visible={modalVisible}
        onSave={handleSaveManualItem}
        onCancel={() => setModalVisible(false)}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  addButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    minHeight: 48,
    justifyContent: 'center',
  },
  addButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  controls: {
    flexDirection: 'row',
    padding: 16,
    gap: 8,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#f5f5f5',
    alignItems: 'center',
    minHeight: 44,
    justifyContent: 'center',
  },
  toggleButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
  },
  clearButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#f44336',
    alignItems: 'center',
    minHeight: 44,
    justifyContent: 'center',
  },
  clearButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f44336',
  },
  list: {
    flex: 1,
  },
  listContent: {
    padding: 16,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 12,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
  },
  emptyText: {
    fontSize: 18,
    color: '#999',
    textAlign: 'center',
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    color: '#bbb',
    textAlign: 'center',
    paddingHorizontal: 32,
  },
});
